### ISSUE TITLE
Help with referral events

### ISSUE THREAD

**Issue by martinstreicher** [GetAmbassador/mbsy#14]
I am unable to get referrals to work. Here is the call I am making...

```
Mbsy::Event.create(
  :auto_create=>1,
  :campaign_uid=>29561,
  :email=>"martin.streicher+2@locomotivellc.com", 
  :email_new_ambassador=>1,
  :revenue=>99, 
  :short_code=>"18964313", 
  :transaction_uid=>"5")
```

I assume that:
* email is the email address of the person that just signed up.
* short_code is the short_code assigned to the referring ambassador.

I do get a new ambassador with that email address. However, I cannot get the referring ambassador to earn any revenue. The response I get is:

```
{
    "referring_ambassador" => {
              "first_name" => nil,
               "last_name" => nil,
                   "email" => nil,
                     "uid" => nil,
              "commission" => nil,
           "balance_money" => 0,
          "balance_points" => 0,
           "memorable_url" => "http://mbsy.co",
        "unique_referrals" => 0,
                 "sandbox" => nil,
                 "custom1" => "",
                 "custom2" => "",
                 "custom3" => ""
    },
              "ambassador" => {
              "first_name" => "",
               "last_name" => "",
              "created_at" => "2015-06-04T15:05:00.837-4000",
                   "email" => "martin.streicher+2@locomotivellc.com",
                     "uid" => nil,
           "balance_money" => "0.00",
          "balance_points" => "0.00",
           "memorable_url" => "http://mbsy.co/realvolve/18964324",
        "unique_referrals" => "0",
            "count_shares" => "0",
                 "sandbox" => "0",
                 "custom1" => "",
                 "custom2" => "",
                 "custom3" => "",
                  "groups" => "2",
          "campaign_links" => [
            [0] {
                        "campaign_uid" => "29561",
                       "campaign_name" => "Test",
                "campaign_description" => "Test",
                      "initial_reward" => {
                    "type_text" => "Flat Monetary",
                    "type_code" => "F",
                       "amount" => "1"
                },
                    "recurring_reward" => {
                    "type_text" => "None",
                    "type_code" => "D",
                       "amount" => "0"
                },
                             "sandbox" => "0",
                             "private" => "0",
                    "facebook_enabled" => "0",
                                 "url" => "http://mbsy.co/cjvhB",
                  "total_money_earned" => "0.00",
                 "total_points_earned" => "0.00",
                    "unique_referrals" => "0"
            }
        ]
    },
                 "company" => {
          "company_name" => "Realvolve",
           "company_url" => "http://www.realvolve.com",
         "company_email" => "martin.streicher@realvolve.com",
            "point_name" => "points",
        "outgoing_email" => "ambassadors@realvolve.com",
            "avatar_url" => "https://ambassador-api.s3.amazonaws.com/generic_avatar.png"
    }
}
```

... which looks right except the top portion is empty. I would expect the short code to be enough to connect the revenue event with an ambassador. 

How do I add a revenue event to referring ambassador? Is the short code the campaign short code? If so, how does one tie that together. 

What URL should the ambassador be sharing? I assumed it was the mbsy.co/realvolve/#### URL. 

Help!.

**Comment by Ambassador** [comment]
Your assumptions are correct, the reason why it's not working is because that isn't short_code of that Ambassador.  You actually used the "Ambassador ID" (which is appended to the end of the Memorable URL) -- the short_code is appended to the campaign URLs.

For example, the short code of the referred party is "cjvhB"
![image](https://cloud.githubusercontent.com/assets/1012132/7987283/871f8754-0aaa-11e5-9a64-ef349eff8255.png)

Once you make that change, it will work.  Thanks!

**Comment by martinstreicher** [comment]
Is the short code unique per ambassador and campaign? I assume so and I assume that I want to send this particular code back to the user as their unique URL to share?

**Comment by Ambassador** [comment]
Yes, it is unique per campaign & ambassador

**Comment by martinstreicher** [comment]
Jeff:

I have a few questions about how we subscribe to your service. 

Our original intent was to assign a referral URL to each of our users. In fact, I have written code to run through existing users and do those allocations. 

We have about 800 users already.

We were also planning to assign a URL whenever a user was added to the system. 

However, if we have to pay a fee for each of our users, whether or not they ever refer someone, the cost might be prohibitive to make so many assignments. 

How does your system work? When is a fee incurred? 

Martin

**Comment by Ambassador** [comment]
Hi Martin,

Please email us at sales@getambassador.com or myself (jeff@getambassador.com)
so can discuss outside of the repo.

Thanks!
