### ISSUE TITLE
Repo Still Active?

### ISSUE THREAD

**Issue by theunixbeard** [GetAmbassador/mbsy#15]
I'm a new customer working on an API integration for my company. We have a Ruby on Rails app. I noticed the most recent commit for this repo is July 17th, 2014 (i.e. almost a year ago).

Is this client library repo up to date with the REST API? Or is it deprecated?

**Comment by chaselee** [comment]
Hi @theunixbeard! The v2 API as been in a stable state for quite a while, which is why the repo hasn't had a lot of updates in a long time. It's definitely not deprecated though. If there's something missing or a pull request you want to submit we're happy and ready to take a look!
