### ISSUE TITLE
Custom Domain for SSO Embed

### ISSUE THREAD

**Issue by geetotes** [GetAmbassador/mbsy#19]
I'm trying to use `Mbsy:SingleSignOn.embed_html` to generate an embed code that points at a custom domain. But from looking at the function (https://github.com/GetAmbassador/mbsy/blob/8fd5487edc8bc4217f573b00b29e0800ca97332a/lib/mbsy/util/single_sign_on.rb) it seems that `getambassador.com` is hard-coded. Is there a way to change this?

**Comment by chaselee** [comment]
@geetotes we went ahead and added this for you. `Mbsy::SingleSignOn.embed_html(email: current_user.email, domain: your_domain)`. let us know if you have any questions!
