### ISSUE TITLE
balance deprecated?

### ISSUE THREAD

**Issue by chevinbrown** [GetAmbassador/mbsy#24]
It appears that the balance endpoint of the ambassador API is deprecated. 

If that is the case, can we please deprecate the methods, or at least get it in the docs?

❤️

**Comment by jarell-lloyd** [comment]
Hi @chevinbrown Thank you for bringing this to our attention. Our documentation has been updated to reflect that the `/balance/add` and `/balance/deduct` methods have been deprecated.
